version: '3.8'

services:
  # FastAPI Backend Service
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: churn_api
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models:ro  # Mount models directory (read-only)
      - ./data:/app/data:ro      # Mount data directory (read-only)
    environment:
      - PYTHONUNBUFFERED=1
      - MODEL_PATH=/app/models/best_model.pkl
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - churn_network

  # Streamlit Frontend Service
  streamlit:
    build:
      context: ./streamlit
      dockerfile: Dockerfile
    container_name: churn_streamlit
    ports:
      - "8501:8501"
    environment:
      - PYTHONUNBUFFERED=1
      - API_URL=http://api:8000  # Use Docker service name
    depends_on:
      api:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - churn_network

networks:
  churn_network:
    driver: bridge

volumes:
  models:
  data: